- name: Copy logrotate settings
  ansible.builtin.template:
    src: ansible-logrotate.j2
    dest: /etc/logrotate.d/ansible-pull
    owner: root
    group: root
    mode: '0644'
  tags:
    - ansible_pull
    - ansible_pull_logrotate

- name: Generate vars file for the wrapper
  ansible.builtin.copy:
    content: |
      # Managed by Ansible
      {{ ansible_pull_wrapper_vars | ansible.builtin.to_nice_yaml(indent=2) }}
    dest: "{{ ansible_pull_wrapper_vars_file }}"
    owner: root
    group: "{{ ansible_pull_group }}"
    mode: '0644'

- name: Create vault password file
  ansible.builtin.template:
    src: vault.j2
    dest: "{{ ansible_pull_vault_password_file }}"
    owner: "{{ ansible_pull_user }}"
    group: "{{ ansible_pull_group }}"
    mode: '0600'
  when: ansible_pull_vault_password_source_file is not defined
  tags:
    - ansible_pull
    - ansible_pull_vault

- name: Copy vault password file
  ansible.builtin.copy:
    src: "{{ ansible_pull_vault_password_source_file }}"
    dest: "{{ ansible_pull_vault_password_file }}"
    owner: "{{ ansible_pull_user }}"
    group: "{{ ansible_pull_group }}"
    mode: '0600'
  when:
    - ansible_pull_vault_password_source_file is defined
  tags:
    - ansible_pull
    - ansible_pull_vault
