- name: Merge default and custom cron job dictionary
  ansible.builtin.set_fact:
    ansible_pull_cron_job: "{{ ansible_pull_cron_job_defaults | combine(ansible_pull_cron_job | default({})) }}"
  tags:
    - ansible_pull
    - ansible_pull_scheduler

- name: Create job to run ansible-pull using {{ ansible_pull_scheduler_type }}
  ansible.builtin.include_tasks: "scheduler/{{ ansible_pull_scheduler_type }}.yml"
  tags:
    - ansible_pull
    - ansible_pull_scheduler
